#Dataset Preprocessing

### Dataset Exploration

In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_path = 'gdrive/My Drive/ProgettoDCML/'

Mounted at /content/gdrive


In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv(root_path+'monitored_data.csv')

In [4]:
cols_to_drop = [] # will contain the columns to drop
cols_to_drop_test_no_memory = []

In [5]:
dataset.head()

0user  0nice  0system  0idle  0iowait  0irq  0softirq  0steal  0guest  \
0    0.0    0.0      0.0    0.0      0.0   0.0       0.0     0.0     0.0   
1    0.0    0.0      0.0    0.0      0.0   0.0       0.0     0.0     0.0   
2    1.0    0.0      0.0    0.0      0.0   0.0       0.0     0.0     0.0   
3    0.0    0.0      0.0    1.0      0.0   0.0       0.0     0.0     0.0   
4    1.0    0.0      0.0    0.0      0.0   0.0       0.0     0.0     0.0   

   0guest_nice  ...  virtual_used  virtual_free  virtual_active  \
0          0.0  ...    3341373440   17960857600      4861186048   
1          0.0  ...    3342172160   17960284160      4860960768   
2          0.0  ...    3338850304   17963515904      4860956672   
3          0.0  ...    3339055104   17966448640      4860923904   
4          0.0  ...    3339448320   17966051328      4861206528   

   virtual_inactive  virtual_buffers  virtual_cached  virtual_shared  \
0        1817047040        350543872      3491561472        48103424   
1        1817047040        350543872      3491336192        48103424   
2        1816911872        350552064      3491418112        48103424   
3        1813766144        350552064      3488280576        44957696   
4        1813766144        350552064      3488284672        44957696   

   virtual_slab        time_s  injector  
0     297951232  1.704296e+09      rest  
1     297951232  1.704296e+09      rest  
2     297619456  1.704296e+09      rest  
3     297926656  1.704296e+09      rest  
4     297664512  1.704296e+09      rest  

[5 rows x 69 columns]

In [6]:
x = list(dataset.columns)[:10]
dataset[x].describe()

0user         0nice       0system         0idle       0iowait  \
count  11252.000000  11252.000000  11252.000000  11252.000000  11252.000000   
mean       0.320121      0.002488      0.033239      0.512620      0.000178   
std        0.723227      0.076550      0.180256      0.783076      0.013332   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      1.000000      0.000000   
max        6.000000      5.000000      2.000000      5.000000      1.000000   

          0irq      0softirq   0steal   0guest  0guest_nice  
count  11252.0  11252.000000  11252.0  11252.0      11252.0  
mean       0.0      0.007110      0.0      0.0          0.0  
std        0.0      0.098622      0.0      0.0          0.0  
min        0.0      0.000000      0.0      0.0          0.0  
25%        0.0      0.000000      0.0      0.0          0.0  
50%        0.0      0.000000      0.0      0.0          0.0  
75%        0.0      0.000000      0.0      0.0          0.0  
max        0.0      2.000000      0.0      0.0          0.0

In [7]:
cols_to_drop.append(['0irq', '0steal', '0guest', '0guest_nice', '0iowait'])
cols_to_drop.append(['1irq', '1steal', '1guest', '1guest_nice', '1iowait'])
cols_to_drop.append(['2irq', '2steal', '2guest', '2guest_nice', '2iowait'])
cols_to_drop.append(['3irq', '3steal', '3guest', '3guest_nice', '3iowait'])

In [8]:
x = list(dataset.columns)[40:44]
dataset[x].describe()

# all of these columns are useful

load0         load1         load2         load3
count  11252.000000  11252.000000  11252.000000  11252.000000
mean      35.557536     31.254168     34.123516     34.446978
std       29.897784     26.229001     30.148775     28.513585
min        0.000000      0.000000      0.000000      0.000000
25%       20.000000     20.000000     16.700000     20.000000
50%       25.000000     25.000000     25.000000     25.000000
75%       44.400000     40.000000     40.000000     40.000000
max      100.000000    100.000000    100.000000    100.000000

In [9]:
x = list(dataset.columns)[44:56]
dataset[x].describe()

0current     0min     0max      1current     1min     1max  \
count  11252.000000  11252.0  11252.0  11252.000000  11252.0  11252.0   
mean    2546.373276    800.0   3400.0   2533.954874    800.0   3400.0   
std      578.926924      0.0      0.0    591.635763      0.0      0.0   
min     1001.701000    800.0   3400.0    976.758000    800.0   3400.0   
25%     2247.784000    800.0   3400.0   2245.813250    800.0   3400.0   
50%     2410.269500    800.0   3400.0   2411.393000    800.0   3400.0   
75%     3206.132500    800.0   3400.0   3201.536250    800.0   3400.0   
max     3392.163000    800.0   3400.0   3388.585000    800.0   3400.0   

           2current     2min     2max      3current     3min     3max  
count  11252.000000  11252.0  11252.0  11252.000000  11252.0  11252.0  
mean    2543.437848    800.0   3400.0   2531.279793    800.0   3400.0  
std      577.718361      0.0      0.0    583.060152      0.0      0.0  
min     1019.550000    800.0   3400.0    955.785000    800.0   3400.0  
25%     2231.938750    800.0   3400.0   2219.159250    800.0   3400.0  
50%     2418.555500    800.0   3400.0   2399.533000    800.0   3400.0  
75%     3202.861750    800.0   3400.0   3201.683500    800.0   3400.0  
max     3392.008000    800.0   3400.0   3392.102000    800.0   3400.0

In [10]:
cols_to_drop.append(['0min', '0max', '1min', '1max', '2min', '2max', '3min', '3max'])

In [11]:
x = list(dataset.columns)[56:68]
dataset[x].describe()

virtual_total  virtual_available  virtual_percent  virtual_used  \
count   1.125200e+04       1.125200e+04     11252.000000  1.125200e+04   
mean    2.514434e+10       2.131719e+10        15.222067  3.464195e+09   
std     0.000000e+00       1.784243e+09         7.095311  1.796348e+09   
min     2.514434e+10       1.034841e+10        10.300000  2.161250e+09   
25%     2.514434e+10       2.155950e+10        12.300000  2.660478e+09   
50%     2.514434e+10       2.161003e+10        14.100000  3.107156e+09   
75%     2.514434e+10       2.204641e+10        14.300000  3.326924e+09   
max     2.514434e+10       2.255743e+10        58.800000  1.436511e+10   

       virtual_free  virtual_active  virtual_inactive  virtual_buffers  \
count  1.125200e+04    1.125200e+04      1.125200e+04     1.125200e+04   
mean   1.756952e+10    4.852158e+09      2.209152e+09     3.573120e+08   
std    1.778560e+09    1.818293e+09      3.199529e+08     3.896710e+06   
min    6.082097e+09    3.423891e+09      1.804497e+09     3.505439e+08   
25%    1.785339e+10    3.946785e+09      1.813574e+09     3.537756e+08   
50%    1.797314e+10    4.481915e+09      2.426827e+09     3.574661e+08   
75%    1.827919e+10    4.852406e+09      2.464868e+09     3.607060e+08   
max    1.880778e+10    1.610138e+10      3.250676e+09     3.635814e+08   

       virtual_cached  virtual_shared  virtual_slab        time_s  
count    1.125200e+04    1.125200e+04  1.125200e+04  1.125200e+04  
mean     3.753309e+09    4.301099e+07  3.094328e+08  1.704299e+09  
std      2.717827e+08    5.796372e+06  1.005590e+07  1.648715e+03  
min      3.483247e+09    2.719744e+07  2.971566e+08  1.704296e+09  
25%      3.494642e+09    3.878093e+07  2.980250e+08  1.704298e+09  
50%      3.827120e+09    4.209050e+07  3.147571e+08  1.704299e+09  
75%      3.829445e+09    4.632166e+07  3.163013e+08  1.704300e+09  
max      5.153305e+09    6.939443e+07  3.515515e+08  1.704302e+09

In [12]:
cols_to_drop.append(['time_s', 'virtual_total'])
cols_to_drop_test_no_memory.append(['virtual_available', 'virtual_percent', 'virtual_used',	'virtual_free',	'virtual_active',	'virtual_inactive',	'virtual_buffers',	'virtual_cached',	'virtual_shared',	'virtual_slab'])

### Dataset Manipulation

In [13]:
!pip install joblib

In [14]:
from sklearn.preprocessing import StandardScaler
from joblib import dump, load

In [15]:
cols_to_drop = [i for cols in cols_to_drop for i in cols] # aggregate columns to drop
cols_to_drop_test_no_memory = [i for cols in cols_to_drop_test_no_memory for i in cols] # aggregate columns to drop for test with no memory info

dataset = dataset.drop(columns=cols_to_drop)
dataset_test_no_memory = dataset.drop(columns=cols_to_drop_test_no_memory)

In [16]:
X = dataset.drop(columns='injector') # remove the label from input set
X_test_no_memory = dataset_test_no_memory.drop(columns='injector')

y = [0 if i == 'rest' else 1 for i in dataset['injector']] # create the labels used for training

In [17]:
standard_scaler = StandardScaler()
standard_scaler_test_no_memory = StandardScaler()

X_std = standard_scaler.fit_transform(X) # transform using a Standard Scaler
X_std_test_no_memory = standard_scaler_test_no_memory.fit_transform(X_test_no_memory)

In [ ]:
dump(standard_scaler, root_path+'standard_scaler.bin', compress=True) # save fitted StandardScaler for later use

['gdrive/My Drive/ProgettoDCML/standard_scaler.bin']

# Training

In [18]:
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, confusion_matrix

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dropout, LSTM, Dense, Flatten
from keras.optimizers import Adam
from keras.losses import BinaryCrossentropy

### Train Test Split

In [19]:
X_train_shuffled, X_test_shuffled, y_train_shuffled, y_test_shuffled = train_test_split(X_std, y, test_size=0.3, shuffle=True) # split shuffling

X_train_shuffled_test_no_memory, X_test_shuffled_test_no_memory, _, _ = train_test_split(X_std_test_no_memory, y, test_size=0.3, shuffle=True)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.2, shuffle=False) # split without shuffling (used in RNN)

X_train_test_no_memory, X_test_test_no_memory, _, _ = train_test_split(X_std_test_no_memory, y, test_size=0.2, shuffle=False)

### RandomForestClassifier

In [ ]:
print("\nNo Memory\n")
random_forest_no_memory = RandomForestClassifier(n_estimators=11, n_jobs=-1)
random_forest_no_memory.fit(X_train_shuffled_test_no_memory, y_train_shuffled)
predicted_proba = random_forest_no_memory.predict_proba(X_test_shuffled_test_no_memory)
predicted = random_forest_no_memory.predict(X_test_shuffled_test_no_memory)
print("Accuracy: ", accuracy_score(y_test_shuffled, predicted))
print("Confusion Matrix: \n", confusion_matrix(y_test_shuffled, predicted))

print("\nNormal\n")
random_forest = RandomForestClassifier(n_estimators=11, n_jobs=-1)
random_forest.fit(X_train_shuffled, y_train_shuffled)
predicted_proba = random_forest.predict_proba(X_test_shuffled)
predicted = random_forest.predict(X_test_shuffled)
print("Accuracy: ", accuracy_score(y_test_shuffled, predicted))
print("Confusion Matrix: \n", confusion_matrix(y_test_shuffled, predicted))


No Memory

Accuracy:  0.581457345971564
Confusion Matrix: 
 [[1747  401]
 [1012  216]]

Normal

Accuracy:  0.981042654028436
Confusion Matrix: 
 [[2124   24]
 [  40 1188]]


In [ ]:
from joblib import dump
dump(random_forest, root_path+'random_forest.bin', compress=3) # save the RandomForestClassifier (best model tested)

['gdrive/My Drive/ProgettoDCML/random_forest.bin']











### Stacking
















In [ ]:
print("\nNo Memory\n")
stacking_classifier = StackingClassifier(estimators=[('lda', LinearDiscriminantAnalysis()),
                                       ('nb', GaussianNB()),
                                       ('dtc', DecisionTreeClassifier())],
                            final_estimator=RandomForestClassifier(n_estimators=7))
stacking_classifier.fit(X_train_shuffled_test_no_memory, y_train_shuffled)
predicted_proba = stacking_classifier.predict_proba(X_test_shuffled_test_no_memory)
predicted = stacking_classifier.predict(X_test_shuffled_test_no_memory)
print("Accuracy: ", accuracy_score(y_test_shuffled, predicted))
print("Confusion Matrix: \n", confusion_matrix(y_test_shuffled, predicted))

print("\nNormal\n")
stacking_classifier = StackingClassifier(estimators=[('lda', LinearDiscriminantAnalysis()),
                                       ('nb', GaussianNB()),
                                       ('dtc', DecisionTreeClassifier())],
                            final_estimator=RandomForestClassifier(n_estimators=7))
stacking_classifier.fit(X_train_shuffled, y_train_shuffled)
predicted_proba = stacking_classifier.predict_proba(X_test_shuffled)
predicted = stacking_classifier.predict(X_test_shuffled)
print("Accuracy: ", accuracy_score(y_test_shuffled, predicted))
print("Confusion Matrix: \n", confusion_matrix(y_test_shuffled, predicted))


No Memory

Accuracy:  0.5710900473933649
Confusion Matrix: 
 [[1648  500]
 [ 948  280]]

Normal

Accuracy:  0.9644549763033176
Confusion Matrix: 
 [[2095   53]
 [  67 1161]]


### Neural Network

In [ ]:
'''
NUM_EPOCHS = 20
BATCH_SIZE = 15 # numbers of samples used for each step

TIME_STEPS = 4 # individual monitored data (row) in each sample
OVERLAP = 2 # used to make two samples overlap

N_FEATURES = X_std.shape[1]
#N_FEATURES = X_std_test_no_memory.shape[1]

INIT_LR = 0.05

model = Sequential([
    LSTM(64, input_shape=(TIME_STEPS, N_FEATURES)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid'),
    Flatten()
])
model.build()
model.compile(
    loss=BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=INIT_LR, decay=INIT_LR / (NUM_EPOCHS * 0.5)),
    metrics=['accuracy']
)
model.summary()
'''

In [83]:
NUM_EPOCHS = 20
BATCH_SIZE = 15 # numbers of samples used for each step

TIME_STEPS = 4 # individual monitored data (row) in each sample
OVERLAP = 2 # used to make two samples overlap

N_FEATURES = X_std.shape[1]
#N_FEATURES = X_std_test_no_memory.shape[1]

INIT_LR = 0.05

model = Sequential([
    LSTM(16, input_shape=(TIME_STEPS, N_FEATURES)),
    Dropout(0.5),
    Dense(16, activation='relu'),
    Dropout(0.5),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid'),
    Flatten()
])
model.build()
model.compile(
    loss=BinaryCrossentropy(),
    optimizer=Adam(learning_rate=INIT_LR, decay=INIT_LR / (NUM_EPOCHS * 0.5)),
    metrics=['accuracy']
)
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_14 (LSTM)              (None, 16)                3520      
                                                                 
 dropout_28 (Dropout)        (None, 16)                0         
                                                                 
 dense_42 (Dense)            (None, 16)                272       
                                                                 
 dropout_29 (Dropout)        (None, 16)                0         
                                                                 
 dense_43 (Dense)            (None, 8)                 136       
                                                                 
 dense_44 (Dense)            (None, 1)                 9         
                                                                 
 flatten_14 (Flatten)        (None, 1)               

In [79]:
X_train = np.array(X_train)
#X_train = np.array(X_train_test_no_memory)
X_test = np.array(X_test)
#X_test = np.array(X_test_test_no_memory)

y_train = np.array(y_train)
y_test = np.array(y_test)

X_samples_train = []
y_samples_train = []

X_samples_test = []
y_samples_test = []

# building training set
for i in range(0, X_train.shape[0], int(TIME_STEPS/OVERLAP)):
  X_sample_train = X_train[i:i+TIME_STEPS]
  y_sample_train = y_train[i:i+TIME_STEPS]
  if X_sample_train.shape[0] == TIME_STEPS and y_sample_train.shape[0] == TIME_STEPS: # to avoid using partial samples
    X_samples_train.append(X_sample_train)
    y_samples_train.append(y_sample_train)

# building test set
for i in range(0, X_test.shape[0], int(TIME_STEPS/OVERLAP)):
  X_sample_test = X_test[i:i+TIME_STEPS]
  y_sample_test = y_test[i:i+TIME_STEPS]
  if X_sample_test.shape[0] == TIME_STEPS and y_sample_test.shape[0] == TIME_STEPS: # to avoid using partial samples
    X_samples_test.append(X_sample_test)
    y_samples_test.append(y_sample_test)


In [80]:
X_samples_train = np.array(X_samples_train)
y_samples_train = np.array(y_samples_train)

X_samples_test = np.array(X_samples_test)
y_samples_test = np.array(y_samples_test)

In [81]:
model.fit(X_samples_train, y_samples_train,
          validation_data=(X_samples_test, y_samples_test),
          batch_size=BATCH_SIZE, epochs=NUM_EPOCHS)

Epoch 1/20
300/300 [==============================] - 5s 7ms/step - loss: 0.2432 - accuracy: 0.9309 - val_loss: 0.2463 - val_accuracy: 0.9257
Epoch 2/20
300/300 [==============================] - 2s 6ms/step - loss: 0.1533 - accuracy: 0.9587 - val_loss: 0.2479 - val_accuracy: 0.9155
Epoch 3/20
300/300 [==============================] - 2s 6ms/step - loss: 0.1257 - accuracy: 0.9664 - val_loss: 0.2461 - val_accuracy: 0.9097
Epoch 4/20
300/300 [==============================] - 2s 5ms/step - loss: 0.1260 - accuracy: 0.9687 - val_loss: 0.2141 - val_accuracy: 0.9257
Epoch 5/20
300/300 [==============================] - 2s 6ms/step - loss: 0.1177 - accuracy: 0.9700 - val_loss: 0.2532 - val_accuracy: 0.9088
Epoch 6/20
300/300 [==============================] - 3s 8ms/step - loss: 0.1240 - accuracy: 0.9680 - val_loss: 0.2240 - val_accuracy: 0.9230
Epoch 7/20
300/300 [==============================] - 2s 5ms/step - loss: 0.1177 - accuracy: 0.9691 - val_loss: 0.2091 - val_accuracy: 0.9324
Epoch 

In [82]:
# NORMAL    loss: 0.0163 - accuracy: 0.9907 - val_loss: 0.7630 - val_accuracy: 0.9230
# NO MEMORY loss: 0.0396 - accuracy: 0.9862 - val_loss: 0.2350 - val_accuracy: 0.9471